### ISSUE TITLE
jQA does not find group in adoc

### ISSUE THREAD

**Issue by StephanPirnbaum** [jQAssistant/jqa-core-framework#10]
jQA fails to find groups and therefore Constraints/Concepts when the adoc does not match a specific structure. This behavior is not documented. 

Example: The maven goal available-rules will not show the group in the following example and therefore, effective-rules contains no concept.

```
[[default]]
[role=group,includesConcepts="report:Dependencies.graphml"]

[[report:Dependencies.graphml]]
[source,cypher,role=concept]
.Package Dependencies
----
// Query
----
```
The adoc can be fixed with adding the following after the group definition.
```
- <<report:Dependencies.graphml>>
```

**Comment by DirkMahler** [comment]
The document is invalid as the id `default` is not annotated at a block/section.
