### ISSUE TITLE
Execute rules in lexicographical order

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-core-framework#26]
As a user I would like to have all rules (constraints, concepts, groups) to be executed in lexicographical order. This would help me get a quicker overview on executed rules and to find a specific rule faster.

**Comment by DirkMahler** [comment]
This conflicts with dependencies between rules. Furthermore in the scope of https://github.com/buschmais/jqa-core-framework/issues/13 an ordering has been implemented to allow using implicit dependencies, see the corresponding section in the user manual: http://buschmais.github.io/jqassistant/doc/1.6.0/#_explicit_and_implicit_rule_dependencies.

**Comment by obfischer** [comment]
I am aware of it. I think can still improve it by building groups seperated by dependencies like this:

    [INFO] Executing concepts with no dependency
    [INFO] .....
    [INFO] Executing concepts with dependencies to the previous group
    [INFO] .....
    [INFO] Executing concepts with dependencies to the previous group
    [INFO] .....
