### ISSUE TITLE
Update org.snakeyaml:snakeyaml-engine to 2.0

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-core-framework#30]
Update `org.snakeyaml:snakeyaml-engine` from version 1.0 to 2.0.

This update is required as the new YAML plugin uses version 2.0 of `org.snakeyaml:snakeyaml-engine`, which is not backward compatible to version 1.0 used by the core framework. As Maven always chooses the highest version of a library, version 1.0 will not be available at the classpath and this leads to `ClassNotFoundExceptions` during the initialisation of the `YamlRuleParserPlugin`.

**Comment by DirkMahler** [comment]
It makes sense to upgrade but to avoid confusion: Maven does not pick the highest but the nearest version in the dependency tree for resolving conflicts. For details see https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html
