### ISSUE TITLE
Automated creation of jqassistant-plugin.xml

### ISSUE THREAD

**Issue by axdotl** [jQAssistant/jqa-core-framework#38]
Maintaining the jqassistant-plugin.xml is quite annoying, especially adding each and every descriptor manually. Because you'll got informed about missing entries not before scanning a project.

Would it possible to generate the xml-file on compile time?

**Comment by obfischer** [comment]
We think that creating and editing the `jqassistant-plugin.xml` is not so high in comparison with the whole effort for creating a plugin. Therefore we will close this issue for now. Feel free to provide a PR for this feature.
