### ISSUE TITLE
Render execution time for applied concepts

### ISSUE THREAD

**Issue by jexp** [jQAssistant/jqa-core-framework#40]

**Comment by StefanPenndorf** [comment]
I vote for this one too. Would have been easier to spot the slow concept if execution times would have been printed out (using maven)

e.g.
```
[INFO] Applying concept 'sx:GuiModule' with severity: 'MINOR'
[INFO] Application of concept 'sx:GuiModule' took 312ms to execute and returned 20 results.
```

**Comment by DirkMahler** [comment]
A warning is now logged if execution time of a rule exceeds 5s (message includes actual execution time).
