### ISSUE TITLE
Sometimes jQAssistant fails to find rules

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-core-framework#5]
There might be a bug or not. 1.1.3 fails currently to load all rules I defined for jQAssistant in `jqa-own-constraints` (at `b7747bfdd8aaf66e2fedb1daff7c98a17b4a57de`). jQAssistant seems not to load the rules defined in `license.xml`. 

We should investigate this for one of the next releases.

**Comment by obfischer** [comment]
I was able to reproduce this bug. The project _jqa-own-constraints_ contains a rule file called `license.xml`, which is currently not used. As soon as I enable the rules in this file, jQA fails in some projects, e.g. _jqa-checkstyle-config_, with the following message:

```
[ERROR] Failed to execute goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.9.0-ALPHA1:analyze (default) on project checkstyle-config: Cannot read rules.: The constraint jqa-legal:license:only-one-in-pom has already defined. -> [Help 1]
```

**Comment by DirkMahler** [comment]
The behavior is as intended as both files contain a constraint with the id ```jqa-legal:license:only-one-in-pom```.
