### ISSUE TITLE
Speedup Rule execution for large multi module maven projects

### ISSUE THREAD

**Issue by StefanPenndorf** [jQAssistant/jqa-core-framework#56]
The performance of jQAssistant in our project degraded vastly over time. Currently it is so bad that we are considering dropping the plugin from our build pipeline.

We've got a Maven Multi Module project with 95 modules having 140.000 LOC. jQAsisstant currently takes 34% of overall CPU usage/build time. Our build including static analysis and jQAssistant currently takes 24 Minutes whereas 9 Minutes will be needed by the analyze goal. During the execution of the goal no other plugins or tasks execute. The very same build without jQAssistant takes 12 minutes.

I could track down the problem with JProfiler a little bit to have two issues: I've reported [the Maven 3 scanner problem](https://github.com/jQAssistant/jqa-maven3-plugin/issues/15) already which seems to be the minor issue.

![image](https://user-images.githubusercontent.com/990538/112001131-f3c53700-8b1e-11eb-96ca-d232f6d25936.png)

The problem with the analyze goal seems to be query execution. I'll launch the build with a reduced ruleset tomorrow. Is there any way to log cipher query execution times?

**Comment by DirkMahler** [comment]
Which version of jQA are you using?

**Comment by StefanPenndorf** [comment]
We've been using 1.8.0 thus upgrading to 1.9.0 brought a speedup for scan (see https://github.com/jQAssistant/jqa-maven3-plugin/issues/15)

Additionally I could track down the problem to a self written Cipher Query:
```
    <concept id="sx:GuiModule">
        <description>Ein Maven-Modul ist ein GUI-Modul, wenn es von Vaadin oder Solar-Vaadin abhängt.</description>
        <cypher><![CDATA[
            MATCH (v:Maven)<-[:DEPENDS_ON*1..6]-(a:Maven:Java)
            WHERE (
                    (v.group="ag.saxess.solar" and v.name="solar-vaadin") OR
                    (v.group="com.vaadin" AND v.name="vaadin-server")
                  )
                  AND (a.type="jar" OR a.type="war")
                  AND a.group="ag.saxess.xxx"
            SET a:GuiModule
            RETURN DISTINCT a
        ]]></cypher>
    </concept>
```
Without the concept (and the constraints that depended on it) I was able to reduce the build time from 8m 28s to 1m 28s.

(Please note I didn't execute the full build today skipping compile, test etc. as opposed to my measures two days ago)

Now I need to find another way to check the rules for GUI modules.

I'll execute the original build tomorrow to record the overall improvement (without the constraints until I've found a replacement)

**Comment by StefanPenndorf** [comment]
To answer my question from the first post 

> Is there any way to log cipher query execution times?

No, at the time of writing there seems to be none, see https://github.com/jQAssistant/jqa-core-framework/issues/40

**Comment by DirkMahler** [comment]
Just a hint: the Maven label does not refer to artifacts. Specify artifacte and and use shortestPath to speed up things:

    MATCH shortestPath((v:Maven:Main:Artifact)<-[:DEPENDS_ON*]-(a:Maven:Main:Artifact))
    WHERE v <> a AND ( ... )

By using the label `:Main` you can as well omit the check for `war` and `jar` types.

**Comment by StefanPenndorf** [comment]
Thanks @DirkMahler  I'll give it a try tomorrow.

Without the slow concept and an upgrade to jQA 1.9.0 I'm at 13 minutes for the original build which is quite acceptable (given that the build takes 12 minutes without jQA the problem is now a different plugin/step of our build)

![image](https://user-images.githubusercontent.com/990538/112497334-cc23d800-8d85-11eb-9f37-971ba2e98795.png)
