### ISSUE TITLE
Allow extension of concepts using "providesConceptId(s)"

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqa-core-framework#59]
A user of jQAssistant should be able to extend existing concepts.

Example: The constraints related by the Spring plugin report violations for generated code (e.g. by Maven plugins). Therefore these rules should exclude generated classes, but sadly there's no general concept to identify them.

The proposed solution is as follows:
- The according Spring constraints require a (new) concept "java:GeneratedType" and filter by the label "Generated"
- This concept itself does nothing except creating a report about artifacts containing Java types with that label
- A user may create project concepts providing to "java:GeneratedType" setting this label

```
<concept id="java:GeneratedType">
    <cypher><![CDATA[
        MATCH
          (a:Artifact)-[:CONTAINS]->(generated:Java:Type:Generated)
        RETURN
          a as Artifact, count(generated) as GeneratedTypes
    ]]></cypher>
</concept>
```

```
<concept id="my-project:GeneratedType">
  <providesConcept refId="java:GeneratedType"
   <cypher><![CDATA[
        MATCH
          (generated:Java:Type)
        WHERE
          generated.fqn starts with "com.acme.generated."
        SET
           generated:Generated
        RETURN
          count(generated) as GeneratedTypes
    ]]></cypher>
```

- [x] We got a final feedback from the reporting user (_if applicable_)
- [x] Unittests have been written (_if applicable_)
- [x] Integration tests have been written (_if applicable_)
- [x] Test coverage is the same or even better then before (_if applicable_)
- [x] Documentation has been written (_if applicable_)
- [x] Added a note on the new feature to the release notes (_if applicable_)

**Comment by obfischer** [comment]
Hi @DirkMahler, do we need this for 1.10.0 or can it be done also for 1.11.0?

**Comment by DirkMahler** [comment]
It's easy to implement, provides high value and actually already nearly finished...
