### ISSUE TITLE
Plugins should be executed using PluginClassloader as TCCL

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqa-core-framework#77]
Some plugins load additional classes using reflection (e.g. Elk support for PlantUML report plugin), this should be supported by the TCCL set to the plugin classloader.

**Comment by StephanPirnbaum** [comment]
Proposal: Register Neo4j procedures and functions by specifying Neo4j plugins directly, e.g.
store:
  plugins:
    - group-id: org.neo4j.procedures
      artifact-id: apoc-core
      version: 5.17.0

And register as shown in:
https://github.com/michael-simons/neo4j-examples-and-tips/blame/master/examples/testing-ogm-against-embedded-with-apoc/src/test/java/org/neo4j/tips/testing/testing_ogm_against_embedded_with_apoc/ApplicationTests.java#L53
