### ISSUE TITLE
JAVA 21 - JQA-Maven-Plugin fails to start Neo4J

### ISSUE THREAD

**Issue by lostiniceland** [jQAssistant/jqa-core-framework#85]
### Bug Description
Running `jqassistant:scan` on JDK 21 using the `jqassisatant-maven-plugin` gives the following error

`[ERROR] Failed to execute goal com.buschmais.jqassistant:jqassistant-maven-plugin:2.0.8:scan (default-cli) on project rechtspruefung-business: Execution default-cli of goal com.buschmais.jqassistant:jqassistant-maven-plugin:2.0.8:scan failed: Error starting Neo4j database server at /home/schlegelm014/development/projects/eamz/rechtspruefung/rechtspruefung-business/target/jqassistant/store/data/databases: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@ff0fb6a' was successfully initialized, but failed to start. Please see the attached cause exception "null". This database is shutdown. Failed to wrap pointer in ByteBuffer. UnsupportedOperationException`

### Expected Behaviour
Running with JDK 21 works as it does with JDK 17

### Your Environment
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Java version: 21, vendor: Azul Systems, Inc., runtime: /opt/BA/java/zulu21.28.85-ca-jdk21.0.0-linux_x64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.10.60.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

### How can we reproduce the bug?
Run scan task with JDK 21 -> fail
Switch to JDK 17 and run again -> success

**Comment by DirkMahler** [comment]
Relates to #62

**Comment by DirkMahler** [comment]
Currenlty jQA is based on Neo4j 4.x which still runs on JDK 17 but not on JDK 21. This is likely to be solved with Neo4j 5.x which has JDK 17 as minimum requirement.

We need to evaluate how to deal with that, there are still plenty of (enterprise) projects out in the wild based where only Java 11 is available, probably getting back to an approach where jQA needs to support multiple Neo4j backends.

**Comment by murdos** [comment]
> Currenlty jQA is based on Neo4j 4.x which still runs on JDK 17 but not on JDK 21. This is likely to be solved with Neo4j 5.x which has JDK 17 as minimum requirement.
> 
> We need to evaluate how to deal with that, there are still plenty of (enterprise) projects out in the wild based where only Java 11 is available, probably getting back to an approach where jQA needs to support multiple Neo4j backends.

@DirkMahler : if there's anything we can do to help, don't hesitate to ask. 
This is actually a blocking issue for my current project, we'll rollback to JDK 17 in order to keep jqassistant working.

**Comment by lostiniceland** [comment]
We've done some testing and it looks like analyzing Java 21 projects while running JQA with Java 17 seems to work. We have to make some more tests though (not that it was just a wrongly configured pipeline)

**Comment by DirkMahler** [comment]
> We've done some testing and it looks like analyzing Java 21 projects while running JQA with Java 17 seems to work. We have to make some more tests though (not that it was just a wrongly configured pipeline)

We'll check the current manual to make this explicit - even if jQA itself requires a specific JDK for running it is possible to scan bytecode complied from latest (LTS) JDE releases.
