### ISSUE TITLE
Enabling auto-selection of the Neo4j backend

### ISSUE THREAD

**Issue by murdos** [jQAssistant/jqa-core-framework#89]
### Feature Description

As a JQAssistant plugin developer
I would like to develop my plugin with java 21
to that it would be nice if jqassistant core libraries could auto-select the neo4j backend depending on java runtime 

### Additional information on the requested Feature
Following this discussion: https://github.com/jQAssistant/jqa-maven-plugin/pull/84#discussion_r1452980144

My personal use case is a plugin that uses some test dependencies such as SpringBoot.
Currently I have to stay with java 11 for developing my plugin, and thus I can't use recent version of SpringBoot (3.x) because it requires java 17.

### How to Test
We could setup a github action build matrix with multiple java LTS versions (11, 17, 21) for some plugins distributed in https://github.com/jqassistant-plugin/

### Definition of Done for the Implementers
- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)

**Comment by DirkMahler** [comment]
Auto-selection of Neo4j-backend is implemented, will be released with 2.1.0.

**Comment by DirkMahler** [comment]
jQA 2.1.0-RC1 is available from Maven Central enabling the auto-selection, can you try? For your plugin you'll need to import the jQA BOM, it does the actual job.

**Comment by murdos** [comment]
I've tested it, and it works fine, thank you!
