### ISSUE TITLE
Persist Concepts from Analyze for testing

### ISSUE THREAD

**Issue by lostiniceland** [jQAssistant/jqa-core-framework#93]
### Feature Description
When designing new Concepts or Constraints it would be very helpful to have a flag (preferably in combination with `reset`) which persists the applied concepts from the analyze step in the local storage.

Currently I have to apply all queries in the right order which constitute my concepts every time the store was reset. This is even more troublesome when concepts from plugins are required: I have to look them up in the documentation and apply them in the correct order.

### Additional information on the requested Feature
This feature is only useful when running against a local Neo4j. We don't want to mess up shared instances.

### How to Test
Run a analyze step which requires some concepts from a plugin. Start the server and query for a plugin or custom concept.
Result must be displayed.

### Definition of Done for the Implementers
_Remove this hint: these checkboxes can be checked like this: [x]_
- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)

**Comment by murdos** [comment]
I may be off-topic if I haven't fully understood your need, but if you have an issue with order of applied concepts, maybe you should declared [dependencies](https://jqassistant.github.io/jqassistant/doc/2.0.7/manual/#_rule_dependencies) between your concepts, using `requiresConcept`?
JQAssistant will then resolved dependencies and apply concepts in the correct order

**Comment by lostiniceland** [comment]
No, it is not about the order of applied concepts during analyze. 
The issue is that after analyze all the concepts applied during analyze are lost when running the local server.

1. `scan` populates local db with scan-results 
2. `analyze` performs queries, sets labels etc only in-memory
3. `server` only sees db in state after `scan`

I understand the rationale, that you can run analyze as often as you like after your initial scan (assuming no changes in bytecode). But for debugging it would be great to persist everything done during analyze.
I've experimented with ` execute-applied-concepts: true` in the ` analyze` config section but this does not what I expected.

**Comment by DirkMahler** [comment]
If I get the problem right then this seems to be an issue with the setup, i.e. the goals probably use different database directories because the configuration differs - you should be able to verify this from the logs.

Do you run jQA with Maven? If so make sure that the jQA setup in your `pom.xml` uses the id `default-cli` or provide `jqassistant.store.uri=file:<absolute path` as a property on the command line.

**Comment by lostiniceland** [comment]
No, we run JQA CLI because we use Gradle and the [Gradle-Plugin](https://github.com/kontext-e/jqassistant-gradle-plugin) seems not to be updated for 2.x. We will test this when we find some time.

**Comment by lostiniceland** [comment]
Looks like I was wrong. Now I am able to see the Concepts. I dont know what changed.
Sorry for the inconvenience.
