### ISSUE TITLE
Config value "NEVER" threw an Exception whilst being converted

### ISSUE THREAD

**Issue by ascheman** [jQAssistant/jqa-core-framework#98]
### Bug Description

When executing the `jqassistant:analyze` Maven goal with the property setting `jqassistant.analyze.report.fail-on-severity=NEVER`, jQA fails with the following Exception:

```
[ERROR] Failed to execute goal com.buschmais.jqassistant:jqassistant-maven-plugin:2.1.0:analyze (default-cli) on project XXX: Execution default-cli of goal com.buschmais.jqassistant:jqassistant-maven-plugin:2.1.0:analyze failed: Configuration validation failed:
[ERROR]         java.lang.IllegalArgumentException: SRCFG00039: The config property jqassistant.analyze.report.fail-on-severity with the config value "NEVER" threw an Exception whilst being converted Cannot convert NEVER to enum class com.buschmais.jqassistant.core.rule.api.model.Severity
```

### Expected Behaviour

Using `NEVER` (or `never`) should be possible according to the docs.

### Definition of Done for the Implementers
- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)

**Comment by DirkMahler** [comment]
The issue has been fixed, will be available with the next upcoming release.
